### ISSUE TITLE
Cannot install usbcalls package 10.299 from Netlabs Exp repo

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/yum-os2#1]
**Describe the bug**
yum version 3.4.3, I am running yum from a commandline:
When I attempt to install usbcalls package 10.299-2.oc00 from Netlabs Exp repo, I get this:

<quote>
Lade Pakete herunter:
Running Transaction Check
ERROR with transaction check vs depsolve:
usbcalls wird ersetzt durch (installiert) libusbcalls-12.04-1.oc00.i686
Bitte melden Sie diesen Fehler unter http://yum.baseurl.org/report
 You could try running: rpm -Va --nofiles --nodigest
</quote>

**Expected behavior**
I would not expect a reference to usbcalls-12.04 (AN specific). I'd rather expect that the selected package is installed.

Is there any way I can force installation of that package ?

**Comment by lerdmann** [comment]
I now see that I have libusbcalls-12.04 installed. However I cannot deinstall it as other packages have dependencies on it:
cups
cups-filters
cups-ipptool
cups-lpd
libusb1
libuvc

Is there a way to deinstall all of that, install usbcalls 10.299 and then reinstall the mentioned packages ?

**Comment by lerdmann** [comment]
Uninstalling all packages, installing usbcalls 10.299-2.oc00 and then reinstalling all packages mentioned above solved the problem. This issue can be closed.

**Comment by SilvanScherrer** [comment]
the yum-replace-plugin could have worked, as we have that plugin as well. https://codybonney.com/upgrade-a-package-using-the-yum-replace-plugin/
